[package]
name = "cairo-args-runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.76"
cairo-felt = "0.8.7"
cairo-lang-compiler = "2.4.0"
cairo-lang-diagnostics = "2.4.0"
cairo-lang-runner = "2.4.0"
cairo-lang-sierra = "2.4.0"
cairo-lang-sierra-generator = "2.4.0"
cairo-lang-starknet = "2.4.0"
cairo-lang-utils = { version = "2.4.0" }
clap = { version = "4.4.11", features = ["derive"] }
scarb = { git = "https://github.com/software-mansion/scarb.git", tag = "v2.4.0" }
termcolor = "1.4.0"
